# Generated by Django 5.1.5 on 2025-01-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersected_by', to='polygons.polygonmodel')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='polygons.polygonmodel')),
            ],
            options={
                'db_table': 'intersections',
            },
        ),
    ]
